# Generated by Django 5.2.9 on 2026-01-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
